from ModelGen.ConceptExtract import Concepts

# from stanfordcorenlp import StanfordCoreNLP
# from nltk.tree import Tree

# from openie import StanfordOpenIE

paragraph = """The Watergate complex is a group of six buildings in the Foggy Bottom neighborhood of Washington, D.C., in the United States. Covering a total of 10 acres (4 ha) adjacent to the John F. Kennedy Center for the Performing Arts, the buildings include:Built between 1963 and 1971, the Watergate was considered one of Washington's most desirable living spaces, popular with members of Congress and political appointees in the executive branch. The complex has been sold several times since the 1980s. In the 1990s, it was split up and its component buildings and parts of buildings were sold to various owners.In 1972, the headquarters of the Democratic National Committee, then located on the sixth floor of the Watergate Office Building, was burglarized; private campaign documents were photographed and telephones were wiretapped. The investigation into the burglary revealed that high officials in the administration of President Richard Nixon had ordered the break-in and then tried to cover up their involvement. Additional crimes were also uncovered. The ensuing Watergate scandal, named for the complex, resulted in President Nixon's resignation on August 9, 1974.The name Watergate and the suffix -gate have since become synonymous with and applied to controversial topics and scandals in the United States and elsewhere.The Watergate superblock is bounded on the north by Virginia Avenue, on the east by New Hampshire Avenue, on the south by F Street, and on the west by the Rock Creek and Potomac Parkway running along the Potomac River. It is in the Foggy Bottom neighborhood, next to the Kennedy Center and the embassy of Saudi Arabia. The nearest Metro station, 0.4 miles (650 m) away, is Foggy Bottom-GWU.For more than a century, the land now occupied by the Watergate complex belonged to the Gas Works of the Washington Gas Light Company, which produced manufactured gas (a mixture of hydrogen, carbon monoxide, methane, and other flammable and nonflammable gases) for heating, cooking, and lighting throughout the city. Gas production ceased at the site in 1947, and the plant was demolished shortly thereafter.In the 1950s, the World Bank considered building its international headquarters here and on the adjacent site (which now houses the Kennedy Center), but rejected the site for unspecified reasons. It constructed its headquarters at its current location at 1818 H Street NW in Washington, D.C.The name Watergate relates to numerous aspects of its physical and historical context.
The complex sits near the eastern terminus of the Chesapeake & Ohio Canal, which operated from 1831 to 1924 and is now a National Historical Park. The remains of the gravity dam across Rock Creek, as well as Waste Weir #1 are at this site. Land once owned by the canal company was part of the site purchased in 1960 by the project's developer, Rome-based Società Generale Immobiliare (SGI).
In his 2018 book The Watergate: Inside America’s Most Infamous Address, author Joseph Rodota gave three accounts of the origin of the name, based on sources inside the development team: Author and playwright Warren Adler, while working as a publicist for the developers, came up with the name; Nicolas Salgo, a New York financier who suggested the original site to Societa Generale Immobiliare, acquired the name from Marjory Hendricks, owner of the Water Gate Inn; and three local executives—Giuseppe Cecchi, an employee of Societa Generale Immobiliare, Nicolas Salgo and Royce Ward—came up with the name, inspired in part by the Water Gate Inn, and recommended it to executives in the Rome office for approval. According to Rodota, the earliest use of the name Watergate in the surviving files of Societa Generale Immobiliare is a June 8, 1961 memorandum authored by Giuseppe Cecchi, summarizing an early meeting with officials of the future John F. Kennedy Center for the Performing Arts about the proposed project.
In his 2009 book Presidential Power on Trial: From Watergate to All the President's Men, William Noble wrote that the Watergate got its name from overlooking the 'gate' that regulated the flow of water from the Potomac River into the Tidal Basin at flood tide. That gate (near the Jefferson Memorial) is about 1½ miles downriver from the Watergate complex.
Another namesake, the Water Gate Inn restaurant (1942–1966), operated on the site for more than two decades before the Watergate complex was built.
In 2004, Washington Post writer John Kelly argued that the name was most directly linked to the Water Steps or Water Gate, a set of ceremonial stairs west of the Lincoln Memorial that led down to the Potomac. The steps had been originally planned as a ceremonial gateway to the city and an official reception area for dignitaries arriving in Washington, D.C., via water taxi from Virginia, though they never served this function. Instead, beginning in 1935, a floating performance stage on the Potomac River was anchored to the base of the steps. It was the site for open-air concerts and the audience could sit on the stairs. Up to 12,000 people would sit on the steps and surrounding grass to listen to symphonies, military bands, and operas. The barge concerts ended in 1965 when jet airliner service began at National Airport and the noise impaired the venue's viability.
The music venue was depicted in scenes in the motion pictures Houseboat and Born Yesterday (1950).
The Watergate complex was developed by the Italian firm SGI. The company purchased the that belonged to the defunct Chesapeake and Ohio Canal in February 1960 for $10 million. The project was announced on October 21, 1960. Luigi Moretti of the University of Rome was the chief architect, and Milton Fischer of the D.C.-based firm of Corning, Moore, Elmore and Fischer the associate architect. The apartment buildings included two-story units on the first and second floors, while the top-floor units had private rooftop terraces and fireplaces. The design for the entire complex also envisioned an electronic security system so extensive that the press claimed intruders will have difficulty getting onto the grounds undetected. Boris V. Timchenko, a noted D.C.-based landscape architect, supervised the design of the grounds, which included more than 150 planters, tiers of fountains designed to create sounds like a waterfall, landscaped rooftop terraces, swimming pools, and a park. Landscape features such as planters would also be used to create privacy barriers between apartments. The complex was the first mixed-use development in the District of Columbia, and was intended to help define the area as a business and residential rather than industrial district. The Watergate complex was intended to be a city within a city, and provide so many amenities that residents would not need to leave. Among these were a 24-hour receptionist, room service provided by the Watergate Hotel, health club, restaurants, shopping mall, medical and dental offices, grocery, pharmacy, post office, and liquor store. At the time, it was also the largest renewal effort in the District of Columbia undertaken solely with private funds.
Initially, the project was to cost $75 million and consist of six 16-story buildings comprising 1,400 apartment units, a 350-room hotel, office space, shops, 19 luxury villas (townhouses), and three-level underground parking for 1,250 vehicles. The Watergate's curved structures were designed to emulate two nearby elements. The first was the proposed Inner Loop Expressway, a curving freeway expected to be built just in front of the Watergate within the next decade. The second was the nearby Kennedy Center, then in the planning stage and whose original design was supposed to be curvilinear. Although the Kennedy Center later adopted a rectangular shape for cost reasons, the Watergate complex's design did not change. Incidentally, the curved structures would also give apartment dwellers an excellent view of the Potomac River. Because of the curves in the structure, the Watergate complex was one of the first major construction projects in the United States in which computers played a significant role in the design work.
Because the District of Columbia is the seat of the United States government, proposals for buildings in the city (particularly those in the downtown area, near federal buildings and monuments) must pass through an extensive, complex, and time-consuming approval process. The approval process for the Watergate complex had five stages. The first stage considered the proposed project as a whole as well as the first proposed building. The remaining four stages considered the four remaining proposed buildings in turn. At each stage, three separate planning bodies were required to give their approval: The National Capital Planning Commission (NCPC), the District of Columbia Zoning Commission (DCZC), and the United States Commission of Fine Arts (USCFA) (which had approval authority over any buildings built on the Potomac River to ensure that they fit aesthetically with their surroundings).
In December 1961, 14 months after the project was publicly announced, the National Capital Planning Commission (NCPC) voiced its concern that the project's 16-story buildings would overshadow the Lincoln Memorial and the proposed National Cultural Center (later to be called the John F. Kennedy Center for Performing Arts). At the time, the District of Columbia had a height limit on all buildings except for those located exclusively along business streets. To obtain a height waiver, SGI would have to include retail office space in the complex, but the site was then zoned only for apartment buildings. Thus, initial approval first had to be won from the District of Columbia Zoning Commission.
By the time the DCZC met to consider approval in mid-April 1962, the cost of the project had been scaled back to $50 million. Because the District of Columbia lacked home rule, DCZC planners were reluctant to act without coordinating with agencies of the federal government. Additionally, many civic leaders, architects, business people, and city planners opposed the project before the DCZC because they feared it was too tall and too large. By the end of April, DCZC had announced that it would delay its decision. The Commission of Fine Arts also had concerns: it felt some of the land should be preserved as public space and objected to the height of the proposed buildings as well as their modern design. Three days after the DCZC meeting, the USCFA announced it was putting a hold on the Watergate development until its concerns were addressed. To counter this resistance, SGI officials met with members of the USCFA in New York City in April 1962 and defended the complex's design. SGI also reduced the planned height of the Watergate to 14 stories from 16. In May 1962, the NCPC reviewed the project. Additional revisions in the design plan pushed the cost back up to $65 million, even though only 17 villas were now planned. Based on this proposal, the NCPC approved the Watergate plan.
With the support of the NCPC, SGI dug in its heels: It declared it was not interested in developing the unsightly, abandoned commercial site unless its basic curvilinear design (now called Watergate Towne) was approved, and it lobbied DCZC commissioners in late May, lecturing them on the District's architectural heritage and the beauty of modern architecture. SGI officials also lobbied the USCFA. Meanwhile, White House staff made it known that the Kennedy administration wanted the height of the complex lowered to . Three key staff were opposed to the project on height grounds: Arthur M. Schlesinger, Jr., Special Assistant to the President; August Heckscher III, Special Consultant on the Arts; and William Walton, a Kennedy family confidante. The three briefed President John F. Kennedy on the issue, but it was not clear who made the decision to request the height reduction or who made the request public. The White House announcement surprised many, and offended federal and city planners, who saw it as presidential interference in their activities.
SGI's chief architect, Gábor Ács, and Watergate chief architect Luigi Moretti flew to New York City on May 17 and defended the complex's design in a three-hour meeting with USCFA members. SGI agreed to shrink three of the planned buildings in the development to 13 stories (112 ft), with the remaining building rising to . SGI also agreed to add more open space by reducing the size of the Watergate to from 1.911 million square feet and by reorienting or re-siting some of the buildings. The USCFA gave its assent to the revised construction plan on May 28, the White House withdrew its objections, and the DCZC gave its final approval on July 13. The final plan broke one building into two, creating five rather than four construction projects. Moretti later admitted he probably would have lowered the height of the buildings anyway, and thought that the approval process had gone relatively smoothly. Construction was expected to begin in spring 1963 and last five years.
The Watergate project faced one final controversy. The group Protestants and Other Americans United for Separation of Church and State began a national letter-writing campaign opposing the project, alleging that the zoning waivers would not have been given had the Vatican not been a major investor in SGI. By mid-November 1962, more than 2,000 protest letters had been sent to Congress and another 1,500 to the White House. But the group's attempt to stop construction failed, and the project went forward.
The project won its $44 million financial backing in late 1962, and its construction permits in May 1963. Construction began on the first building, the Watergate East apartment, in August 1963. The builder was Magazine Bros. Construction. Groundbreaking occurred in August 1963, and major excavation work was complete by May 1964.
The U.S. Commission on Fine Arts attempted once more to revise the project. In October 1963, the USCFA alleged that the height of the Watergate complex, as measured from the parkway in front of it, would exceed the agreed-upon height restrictions. SGI officials, however, contended that architects are required by law to measure from the highest point on the property on which they are to build; using this measurement, the building met the May 1962 agreement stipulations. On January 10, 1963, SGI and the USCFA agreed that the height of the complex would not exceed above water level (10 inches below that of the nearby Lincoln Memorial), that fewer than 300 apartment units would be built (to reduce population congestion), and to eliminate the proposed luxury villas (to create more open space). Luxury penthouse apartments, however, could extend above the limit if they were set back from the edge of the building and the 14th floor was foregone. With these adjustments, the total cost of the first apartment complex (excluding plumbing, electricity, and decoration) was estimated at $12,184,376.
Construction proceeded. The foundation and basement of the first building, the Watergate East, were completed by September 1964, and the metal and concrete superstructure rose in October. In September 1964, the Watergate's developers signed a first-of-its-kind agreement under which the Washington Gas Light Co. would provide the entire complex with its heating and air conditioning. The Watergate East was completed in May 1965, and a month later the first model apartment unit was opened to the public for viewing. The building formally opened on October 23, 1965, and the first tenants moved in a few days later. Prices for the 238 cooperative apartment units ranged from $17,000 for efficiencies to more than $250,000 for penthouses, and were almost completely sold out by April 1967. The average apartment contained two bedrooms, two-and-a-half baths, a dining room, and a kitchen, and cost $60,000. Each parking space in the underground garage cost $3,000. The tenants took title to their building on April 8, 1966. In November, a Safeway supermarket, a Peoples Drug (now known as CVS pharmacy), beauty salon, barber shop, bank, bakery, liquor store, florist, dry cleaner, post office, upscale shops, and high-end restaurant took up residency in the retail space on the ground floor. Riverview Realty was the leasing agent for the complex.
Construction began on the second building, the 11-story office building and hotel, in February 1965. Both opened on March 30, 1967; the Watergate Hotel welcomed its first guests the same day. The 12-story hotel initially included 213 rooms, while the 12-story office building, attached to the hotel by a colonnade, had of office space. The combined hotel/office building included a health club, space on the ground floor for shops, and a restaurant, the Roman Terrace, on the top floor. Later in April, the Democratic National Committee leased office space in the building's retail office portion.
The third building in the complex, Watergate South, opened in June 1968. It contained 260 residential units, more than any other building in the complex.
Construction on the fourth building in the complex, the Watergate West apartments, began in July 1967. Apartments in the unfinished building, priced from $30,000 to $140,000, began selling in October 1967, an indication of how popular the complex was with District residents. The Watergate West topped out on August 16, 1968, at which point the cost of the project had risen to $70 million. Construction was completed in 1969.
Controversy arose over the construction of the Watergate Office Building, the complex's fifth and final structure. Its original design called for a structure with the upper floors set back to create more space and light. But in June 1965, as excavation and clearing began for the Kennedy Center, its advocates began agitating to lower the planned height of the final Watergate building. The general counsel for the Kennedy Center told the USCFA that the Watergate Town (the development had dropped the e) was planning a building that would harm the aesthetics of the Kennedy Center and intrude on its park-like surroundings. The Watergate's attorneys responded that their building would stay within the agreed-upon height.
The disagreement continued for nearly two years, delaying the planned fall 1967 start to construction. Watergate apartment residents such as Senator Wayne Morse lobbied the USFCA, DCZC, and NCPC to force SGI to accede to the Kennedy Center's wishes. In November 1967, the USCFA reaffirmed its approval of the Watergate project. When the DCZC appeared on the verge of giving its approval as well, the Kennedy Center argued that the DCZC had no jurisdiction over the controversy. The DCZC disagreed, and re-asserted its jurisdiction. The Kennedy Center then argued that the DCZC had not properly considered its objections, and should delay its approval pending further hearings. The District's legal counsel disagreed, giving the DCZC the go-ahead to reaffirm (or not) its approval ruling, which the Zoning Commission did on November 30, 1967.
Although it appeared that SGI was winning the legal battle over the fifth building, D.C. city planners attempted to mediate the dispute between the Kennedy Center and the Watergate and achieve a contractual rather than legal solution. Three separate proposals were made to both sides on December 7, 1967. On April 22, 1968, SGI agreed to turn its fifth building slightly to the southwest in order to open up the Watergate complex a little more and give the Kennedy Center a bit of open space. Although the Kennedy Center accepted the proposal, it demanded that the fifth building include apartment units, rather than be completely devoted to office space, to maintain the area's residential nature. The fight now moved to the NCPC. In June 1968, the NCPC held a hearing at which more than 150 Watergate apartment residents clashed with SGI officials over the nature of the final building. On August 8, 1968, SGI and the Kennedy Center reached a resolution, agreeing that only 25 percent of the fifth building's would be used as office space and that the remaining space would become apartment units. The NCPC approved the revised plan in November 1968, and the DCZC did so five weeks later, specifically zoning the building for nonprofit and professional use only.
The fifth building was completed in January 1971. Its first tenant was the Insurance Institute for Highway Safety, which secured occupancy in February 1971, and its first major tenant was the Manpower Evaluation and Development Institute, which leased the entire eighth floor. In October 1972, several high-end fashion boutiques, jewelers, and a restaurant opened in a retail space named Les Champs.
The total cost of the project was $78 million.
The Watergate's initial reception was poor, but the complex soon became recognized as one of D.C.'s finest examples of modern architecture. When models of the Watergate were unveiled in 1961, critics said the structure would ruin the waterfront. Other critics denounced it as nonconforming and decried it as Antipasto on the Potomac. As noted above, many individuals also felt the complex blocked views of the Potomac River, tended to overshadow nearby monuments and other buildings, and consumed too much open space. Some residents even felt the construction of the units was substandard. Architectural critics called the detailing clunky.
The Washington Star newspaper, however, was an early proponent of the Watergate. In May 1962, it editorialized: It is true that the so-called 'curvilinear' design is at variance with most commercial architecture in Washington. But in our opinion the result, which places a premium on public open space and garden-like surroundings, and which proposes a quality of housing that would rank with the finest in the city, would be a distinct asset. The curving design has continued to draw praise. A noted 2006 guidebook to the city's architecture concluded that the Watergate brought a welcome fluidity to the city's boxy look. Others praised the complex's internal public spaces. When the Watergate East opened in 1965, The Washington Post called these areas opulent and evocative of the best in Italian design. The New York Times characterized the design as sweeping, and complimented each building's spectacular views of the Potomac River, Virginia skyline, and monuments. Many residents later said the flowing lines reminded them of a graceful ship.
In 1970, as the Watergate was nearing completion, SGI proposed building a Watergate II apartment, hotel, and office complex on the waterfront in Alexandria, Virginia, across the Potomac River from the original Watergate. Although the project initially received support from Alexandria city officials and business people, residents of the city's Old Town strongly objected. The project stalled for two years due to protests from residents and a land dispute regarding title to the waterfront land on which the project was to be sited.
The Watergate II project was eventually abandoned in favor of a much larger complex near Landmark Mall in Alexandria (a site nowhere near water).
The entire Watergate complex was initially owned by Watergate Improvements, Inc., a division of SGI. In 1969, the Vatican sold its interest in SGI and no longer was part-owner of the Watergate. Although the Watergate was considered one of the most glamorous residences in the city, as early as 1970 residents and businesses complained of substandard construction, including a leaking roof and poor plumbing and wiring.
The three Watergate Apartment buildings total some 600 residential units. Among the many notable past occupants are the following: Alfred S. Bloomingdale, Anna Chennault, Bob and Elizabeth Dole (Watergate South), Plácido Domingo, Ruth Bader Ginsburg (Watergate South), Alan Greenspan, Monica Lewinsky (she stayed briefly at her mother's apartment in the complex), Senator Russell Long, Clare Boothe Luce (after 1983), Robert McNamara, John and Martha Mitchell, Paul O'Neill, Condoleezza Rice, Mstislav Rostropovich, Maurice Stans, Ben Stein, Herbert Stein, John Warner and Elizabeth Taylor (during their marriage), Caspar Weinberger, Charles Z. Wick, and Rose Mary Woods. The Watergate's popularity among members of Congress and high-ranking executive branch political appointees has remained strong ever since the complex opened. So many members of the Nixon administration settled there that the Washington, D.C., press commented on it and nicknamed it the Republican Bastille. The complex enjoyed a renaissance during the early 1980s and became known as the White House West due to the large number of Reagan administration officials living there.
The Watergate complex changed hands in the 1970s, and each building was sold off separately in the 1990s and 2000s (decade) (see below). Strict lease agreements, however, have kept the apartment buildings in residents' hands: In the Watergate South, for example, owners cannot rent their unit until a full year has passed, and no lease may last more than two years. In 1977, one of the Watergate's financiers (Nicholas Salgo) and Continental Illinois Properties bought SGI's stake in the development for $49 million. Two years later, Continental Illinois sold its interest to the National Coal Board Pension Fund in the U.K. Salgo did the same in 1986. The coal board pension fund put the Watergate complex up for sale in 1989, and estimated the complex's worth at between $70 million and $100 million. Several buildings were sold in the 1990s (for details, see below). The property was valued at $278 million in 1991. Efficiency units in that year sold for $95,000, while penthouse apartments went for $1 million or more. Various buildings were sold again in the early 2000s (decade). In 2005, all of the retail space in the complex was put up for sale.
Little redevelopment of the site has occurred in the 40 years since the Watergate was first built. The complex still includes three luxury apartment buildings, the hotel/office building, and two office buildings. The entire development was listed on the National Register of Historic Places on October 21, 2005.
The Watergate East apartment building is probably the second-best known of the five buildings in the development. It became the most sought-after living location in the city when it opened in 1966.
Problems with the building's construction became apparent shortly after its occupancy. The roof was leaking by 1968. The Washington Post published reports in October 1968 that SGI refused to fix the leaks unless residents dropped their opposition to the construction of the complex's fifth building. By 1970, problems at Watergate East led the press to dub the building the Potomac Titanic, and its residents filed suit against the developer in 1971 to correct the structure's problems. Another lawsuit, filed in February 1970, sought exclusive access to the underground parking garage the cooperative claimed as its own, and demanded that the developer stop selling spaces in the residents' parking area. SGI filed a $4 million counterclaim alleging malicious embarrassment and five years later paid residents $600,000 to settle the cases.
The Watergate East was also the site of a major protest in 1970. In the weeks prior to the jury verdict in the trial of the Chicago Seven (in Chicago, Illinois), political activists began planning and then advertising that a protest would occur at the home of United States Attorney General John N. Mitchell (who lived in the Watergate East). As expected, the verdict was handed down on February 18, 1970 (all the defendants were found not guilty of conspiracy but five were found guilty of incitement to riot). That night, more than 200 people rallied at D.C.'s All Souls Unitarian Church to prepare for the mass protest demonstration the next day. On February 19, several hundred protestors gathered in front of the Watergate East and attempted to enter the building. Several hundred police, bused in to prevent the demonstration, engaged in street fighting with protestors, forced them to retreat, and eventually launched several tear gas canisters to disperse the crowd. More than 145 protesters were arrested. Although a second protest was expected the following day, it never emerged and police spent the day drinking coffee and eating cookies and pastries baked at the Watergate East's pastry shop.
The Watergate East tenants' cooperative refinanced its mortgage some time after 2000, and bought the land beneath its building.
The Watergate Hotel and Office Building is one of the five buildings in the Watergate development.
Management and ownership of the hotel have changed several times since the mid-1980s. In 1986, Cunard Line, the cruise ship company, took over management of the hotel and began redecorating and refurbishing it. The British Coal Board pension fund sold the hotel portion of the building to a British-Japanese consortium in 1990 for $48 million. Blackstone Real Estate Advisors, the real estate affiliate of the Blackstone Group, bought the hotel for $39 million in July 1998. For a few years in the late 1990s and early 2000s (decade), the Watergate Hotel was operated by the Swissôtel hotel group. But the hotel underperformed other Swissôtel operations of similar size, location, and price. Jean-Louis Palladin's eponymous restaurant in the building closed in 1996. The hotel subsequently underwent a renovation in 2000. Swissôtel was purchased by Raffles Hotels and Resorts, and Raffles' management contract ended in May 2002. Blackstone began managing the hotel, and put it up for sale in the fall of 2002 (with an asking price of $50 million to $68 million). Monument Realty bought the hotel for $45 million in 2004 and planned to turn it into luxury apartment co-ops. But many residents in other parts of the complex (some of whom owned the 25 percent of the hotel not sold to Blackstone) argued that a hotel would better enhance the livability of the area and challenged the conversion in court. The hotel closed on August 1, 2007, for a $170 million 18-month renovation, during which the hotel rooms were intended to be roughly doubled in size to . But the renovation never occurred, and the building sat empty—consuming $100,000 to $150,000 a month in security, heating, electricity, water, and other costs. Lehman Brothers, Monument Realty's financing partner, went bankrupt in 2008 and Monument was forced to attempt to sell the property. No buyer emerged and the Blackstone Group regained ownership of the hotel.
The Blackstone Group transferred the Watergate Hotel to its Trizec Properties subsidiary. Trizec did not pay the hotel's property taxes for 2008 (which amounted to $250,000), and estimated that it would take $100 million to make the hotel habitable due to the stalled 2007 renovation. The hotel was put on the market in May 2009, but once again no buyer emerged. The hotel was auctioned off on July 21, 2009 (with the minimum bid beginning at $25 million), but there were no buyers and Deutsche Postbank, which held the $40 million mortgage on the property, took over ownership. The bank began marketing the property for sale, and Monument Realty submitted a bid in October 2009 to buy the hotel back. Monument was outbid by developer Robert Holland and the Jumeirah Group (a luxury hotel chain based in Dubai), but the deal collapsed in November 2009 when financing fell through. Euro Capital Properties purchased the hotel in May 2010 for $45 million, with plans to rehabilitate it over the next two years.
Euro Capital announced its year-long, $85 million renovation of the hotel in January 2013. Among the improvements it wished to make were the addition of six outdoor summer gardens where liquor may be served. The plan would require the approval of the Advisory Neighborhood Commission, which voted to protest the liquor licenses unless the company reached an agreement with all the tenant associations in the Watergate cooperative. A year later, the company said its design team, led by the architectural firm BBGM, had completed a plan to increase the number of luxury hotel rooms to 251 to 348, renovate the lobby to add a bar and lounge, add a restaurant with some outdoor seating, and add a rooftop bar with a small water feature. Euro Capital also said it would seek a hotel management company to continue to operate the Watergate Hotel as an independent hotel. Construction on the new interior elements is planned to start in March 2014.
Euro Capital received the construction permits for its now $100 million renovation in May 2014. Architect Bahram Kamali of BBGM said the renovation will completely replace the electrical, HVAC, mechanical, and plumbing (fresh water and sewage) systems. The renovation now featured two new restaurants, upgraded ballrooms, and a new spa and fitness area. The meeting space, which was quite small by industry standards, was expanded to , and the ballroom enlarged slightly to . Watergate officials said the new rooftop bar will seat 350, and other internal structural changes will add nearly 100 guest rooms. Kamali said the interior will feature high-quality, expensive plaster, stone, and wood finishes, but the exterior's iconic textured concrete balconies will remain unchanged except for repairs, repainting, and new windows. Grunley Construction will oversee all the renovations. Israeli artist and interior decorator Ron Arad designed all the metal sculptures and other work that will be featured in the hotels' bar, lobby, and other interior space.
The cost of the renovation was pegged by Euro Capital at $125 million in November 2014. The 336-room hotel reopened in 2016, nine years after it closed.
The office building portion of the building contains .
In 1972, the headquarters of the Democratic National Committee (DNC) occupied the entire sixth floor of the 11-story building at 2600 Virginia Avenue. The DNC had occupied the space since the building opened in 1967. On May 28, 1972, a team of burglars working for President Richard M. Nixon's re-election campaign bugged the phones of and took photos in and near the DNC chairman's office. The phone taps were monitored from the burglars' rooms (first Room 419, later Room 723) at the Howard Johnson's Motor Lodge across the street at 2601 Virginia Avenue NW. During a second burglary on June 17, 1972, to replace a malfunctioning phone tap and collect more information, five of the burglars were arrested and the Watergate scandal began to unfold. A plaque on the sixth floor of the office building portion of the Watergate Hotel commemorates the break-in. The sixth floor space, occupied by SAGE Publishing since 2015, houses a private exhibit commemorating the break-in and ensuing scandal.
The break-in at the Democratic National Headquarters was not the first break-in at the Watergate. The first break-in, however, shares a remarkable connection with the DNC burglary. The first break-in at the complex was the burglary of a residential unit in 1969. The victim was Rose Mary Woods, President Nixon's personal secretary. The burglars took jewelry and some personal items. Woods would later be accused of erasing 18 and a half minutes from President Nixon's secret Oval Office audio taping system—specifically, the tape from June 20, 1972, that proved central to the Watergate scandal.
In 1993, the British coal board pension fund sold the office portion of the building (as well as the land under two of the three Watergate apartment buildings) to The JBG Companies (an American firm) and Buvermo Properties Inc. (a Dutch company). In 1997, JBG Cos. and Buvermo Properties sold the office building to the Blackstone Group's Trizec Properties division. Trizec put the office building up for sale for $100 million in 2005 and sold it to BentleyForbes Acquisitions LLC, a private firm owned by C. Frederick Wehba and members of the Los Angeles-based Webha family. BentleyForbes put the office tower up for sale on March 12, 2009. In November 2011, after 20 months on the market, the office building sold for $76 million to the Penzance Cos.
In mid-2012, the office building's new owner began a multimillion-dollar upgrade to the Watergate Office Building's lobby, common areas, and Virginia Avenue entrance. The modernization was complete in December 2012, and the building began leasing space again in January 2013. Hitt Contracting designed the renovations, and oversaw the construction.
Penzance sold the office building to a subsidiary of Rockwood Capital for $75 million at the end of 2016. Penzance retained a small ownership stake in the structure, and said it would continue to manage it for Rockwood.
Among the notable people who have lived at the Watergate South is former Secretary of State Condoleezza Rice. As with the Watergate East, residents of this building have discussed buying the land beneath their building, but there is no urgency as the lease on the land does not expire until 2070.
Construction problems and leaks at Watergate West led the press to ridicule this building, like others in the complex, as the Potomac Titanic. On March 2, 1971, residents of the Watergate West filed a lawsuit against SGI in which they claimed their units had defective stoves, faulty air conditioning, leaky windows and balconies, and deficient plumbing. SGI said the problems were similar to those with any new building, and that it had already spent $300,000 on repairs.
Like the Watergate East, residents of this building have discussed buying the land beneath their building but do not need to do so until the land lease expires in 2070.
Britain's National Coal Board Pension Fund sold the Watergate Office Building to John Hancock Mutual Life Insurance in the early 1990s. The building underwent a renovation of its office spaces in 1994. The building saw extensive renovations in 1997.
The Atlantic magazine owner David G. Bradley purchased the office building in 2003. The new owner renovated the building again, a project which included expanding its lobby and restaurant space.
In March 2017, Washington Real Estate Investment Trust (WashREIT) purchased the building from Bradley for $135 million. Under terms of the agreement, Bradley will also become owner of an operating unit within WashREIT. The new building owner said it would continue renovating various spaces in the structure, as well as upgrade and expand the rooftop amenities and build a new fitness center and new conference center."""

# with StanfordOpenIE() as client:

#     for triple in client.annotate(sentence):
#         print('|-', triple)

concepts = Concepts(paragraph)
print(concepts.get())

# nlp = StanfordCoreNLP('stanford-corenlp-full-2018-10-05')

# def extract_phrase(tree_str, label):
#     phrases = []
#     trees = Tree.fromstring(tree_str)
#     for tree in trees:
#         for subtree in tree.subtrees():
#             if subtree.label() == label:
#                 t = subtree
#                 t = ' '.join(t.leaves())
#                 phrases.append(t)
#     return phrases

# # sentence = nlp.word_tokenize(sentence)
# tree_str = nlp.parse(sentence)
# print(tree_str)

# nps = extract_phrase(tree_str, 'NP')
# print(nps)
# vps = extract_phrase(tree_str, 'VP')
# print(vps)